using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace reze
{
    public class player : MonoBehaviour
    {
        public float bulletTime = 0.1f;

        private float reloadTime = 0f;
        Rigidbody thisRigi;
        
        public float speed = 2.0f;

        public GameObject objBullet;

        public Transform Bulletpoint; 

        // Start is called before the first frame update
        void Start()
        {
            thisRigi =this.GetComponent<Rigidbody>();

        }
        private void Move()
        {
            float moveX = Input.GetAxis("Horizontal");
            float moveZ = Input.GetAxis("Vertical");
            
            Vector3 move = new Vector3(moveX, 0.0f, moveZ);
            thisRigi.velocity=move * speed;

            Vector3 poslnWorld = Camera.main.WorldToScreenPoint(this.transform.position);

            float posX = Mathf.Clamp(poslnWorld.x, 0, Screen.width);
            float posZ = Mathf.Clamp(poslnWorld.y, 0, Screen.height);

            Vector3 poslnScreen = Camera.main.ScreenToWorldPoint(new Vector3(posX, posZ, 0));

            thisRigi.position = new Vector3(poslnScreen.x, 0, poslnScreen.z);

        }
        // Update is called once per frame
        void Update()
        {
        Move();
        }
    }
}
